/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package matrodriguezpa.receiptmanager.view;

/**
 *
 * @author Usuario
 */
public class DailyTransactions extends javax.swing.JPanel {

    /**
     * Creates new form DailyExpenses
     */
    public DailyTransactions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expensesScroll = new javax.swing.JScrollPane();
        dailyExpenses = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        dailyExpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Descripción", "Valor", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        expensesScroll.setViewportView(dailyExpenses);

        add(expensesScroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dailyExpenses;
    private javax.swing.JScrollPane expensesScroll;
    // End of variables declaration//GEN-END:variables
}
