/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package matrodriguezpa.onespencer;

/**
 *
 * @author Usuario
 */
public class MonthlyExpenses extends javax.swing.JPanel {

    /**
     * Creates new form MonthlyExpenses
     */
    public MonthlyExpenses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expensesScroll2 = new javax.swing.JScrollPane();
        dailyExpenses1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        expensesScroll2.setMaximumSize(new java.awt.Dimension(600, 200));

        dailyExpenses1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clase uno", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        dailyExpenses1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Gasto", "Matriz", "Razón social", "Monto", "Suma de gasto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        dailyExpenses1.setMaximumSize(new java.awt.Dimension(600, 600));
        dailyExpenses1.setMinimumSize(new java.awt.Dimension(600, 60));
        dailyExpenses1.setPreferredSize(new java.awt.Dimension(450, 60));
        expensesScroll2.setViewportView(dailyExpenses1);

        add(expensesScroll2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dailyExpenses1;
    private javax.swing.JScrollPane expensesScroll2;
    // End of variables declaration//GEN-END:variables
}
