/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package matrodriguezpa.onespencer.view;

/**
 *
 * @author Usuario
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        mainTableScroll = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        bottomBar = new javax.swing.JToolBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(250, 0), new java.awt.Dimension(32767, 0));
        jPanel1 = new javax.swing.JPanel();
        addYearWorkbook = new javax.swing.JToolBar();
        addWorkBook = new javax.swing.JButton();
        addWorkBook1 = new javax.swing.JButton();
        autoMonthlyBoudget = new javax.swing.JToolBar();
        autoBudgetLabel = new javax.swing.JLabel();
        autoBudgetCheckBox = new javax.swing.JCheckBox();
        monthlyBudget = new javax.swing.JTextField();

        main.setLayout(new java.awt.BorderLayout());

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Expense date", "Company name", "Amount", "Expense", "Matrix", "Payment Method"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        mainTable.setEnabled(false);
        mainTableScroll.setViewportView(mainTable);

        main.add(mainTableScroll, java.awt.BorderLayout.CENTER);

        bottomBar.setRollover(true);
        bottomBar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        bottomBar.setEnabled(false);
        bottomBar.add(filler1);

        main.add(bottomBar, java.awt.BorderLayout.PAGE_END);

        addYearWorkbook.setRollover(true);
        addYearWorkbook.setMaximumSize(new java.awt.Dimension(150, 30));
        addYearWorkbook.setMinimumSize(new java.awt.Dimension(150, 30));
        addYearWorkbook.setPreferredSize(new java.awt.Dimension(150, 30));
        addYearWorkbook.setRequestFocusEnabled(false);

        addWorkBook.setBackground(new java.awt.Color(51, 102, 255));
        addWorkBook.setForeground(new java.awt.Color(255, 255, 255));
        addWorkBook.setText("AddProyect");
        addWorkBook.setFocusable(false);
        addWorkBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addWorkBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addYearWorkbook.add(addWorkBook);

        addWorkBook1.setBackground(new java.awt.Color(51, 102, 255));
        addWorkBook1.setForeground(new java.awt.Color(255, 255, 255));
        addWorkBook1.setText("AddMonth");
        addWorkBook1.setFocusable(false);
        addWorkBook1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addWorkBook1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addWorkBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWorkBook1ActionPerformed(evt);
            }
        });
        addYearWorkbook.add(addWorkBook1);

        autoMonthlyBoudget.setRollover(true);
        autoMonthlyBoudget.setMaximumSize(new java.awt.Dimension(200, 30));
        autoMonthlyBoudget.setMinimumSize(new java.awt.Dimension(200, 30));
        autoMonthlyBoudget.setPreferredSize(new java.awt.Dimension(200, 30));

        autoBudgetLabel.setText("Auto Monthly budget");
        autoMonthlyBoudget.add(autoBudgetLabel);

        autoBudgetCheckBox.setSelected(true);
        autoBudgetCheckBox.setFocusable(false);
        autoBudgetCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        autoBudgetCheckBox.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        autoMonthlyBoudget.add(autoBudgetCheckBox);

        monthlyBudget.setMaximumSize(new java.awt.Dimension(80, 30));
        monthlyBudget.setMinimumSize(new java.awt.Dimension(80, 26));
        monthlyBudget.setPreferredSize(new java.awt.Dimension(80, 10));
        autoMonthlyBoudget.add(monthlyBudget);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(addYearWorkbook, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(autoMonthlyBoudget, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addYearWorkbook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autoMonthlyBoudget, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        main.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addWorkBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWorkBook1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addWorkBook1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addWorkBook;
    private javax.swing.JButton addWorkBook1;
    private javax.swing.JToolBar addYearWorkbook;
    private javax.swing.JCheckBox autoBudgetCheckBox;
    private javax.swing.JLabel autoBudgetLabel;
    private javax.swing.JToolBar autoMonthlyBoudget;
    private javax.swing.JToolBar bottomBar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel main;
    private javax.swing.JTable mainTable;
    private javax.swing.JScrollPane mainTableScroll;
    private javax.swing.JTextField monthlyBudget;
    // End of variables declaration//GEN-END:variables
}
