/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package matrodriguezpa.allexpence.view;

/**
 *
 * @author Usuario
 */
public class Export extends javax.swing.JPanel {

    /**
     * Creates new form Export
     */
    public Export() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        autoMonthlyBoudget = new javax.swing.JToolBar();
        autoBudgetLabel = new javax.swing.JLabel();
        autoBudgetCheckBox = new javax.swing.JCheckBox();
        monthlyBudget = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        mainTableScroll = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        expensesScroll2 = new javax.swing.JScrollPane();
        dailyExpenses1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        Middle = new javax.swing.JScrollPane();
        jToolBar2 = new javax.swing.JToolBar();
        jTable8 = new javax.swing.JTable();
        jTable9 = new javax.swing.JTable();
        jTable10 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        jScrollPane18 = new javax.swing.JScrollPane();
        jToolBar3 = new javax.swing.JToolBar();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTable13 = new javax.swing.JTable();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTable14 = new javax.swing.JTable();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTable15 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        autoMonthlyBoudget.setRollover(true);
        autoMonthlyBoudget.setMaximumSize(new java.awt.Dimension(200, 30));
        autoMonthlyBoudget.setMinimumSize(new java.awt.Dimension(200, 30));
        autoMonthlyBoudget.setPreferredSize(new java.awt.Dimension(200, 30));

        autoBudgetLabel.setText("Auto Monthly budget");
        autoMonthlyBoudget.add(autoBudgetLabel);

        autoBudgetCheckBox.setSelected(true);
        autoBudgetCheckBox.setFocusable(false);
        autoBudgetCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        autoBudgetCheckBox.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        autoMonthlyBoudget.add(autoBudgetCheckBox);

        monthlyBudget.setMaximumSize(new java.awt.Dimension(80, 30));
        monthlyBudget.setMinimumSize(new java.awt.Dimension(80, 26));
        monthlyBudget.setPreferredSize(new java.awt.Dimension(80, 10));
        monthlyBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyBudgetActionPerformed(evt);
            }
        });
        autoMonthlyBoudget.add(monthlyBudget);

        jSplitPane1.setLeftComponent(autoMonthlyBoudget);

        add(jSplitPane1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Expense date", "Company name", "Amount", "Expense", "Matrix", "Payment Method"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        mainTable.setEnabled(false);
        mainTable.setMaximumSize(new java.awt.Dimension(700, 700));
        mainTableScroll.setViewportView(mainTable);

        jPanel1.add(mainTableScroll, java.awt.BorderLayout.CENTER);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Enero", "Febrero", "Marzo", "Noviembre", "Diciembre" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setMaximumSize(new java.awt.Dimension(300, 90));
        jList1.setMinimumSize(new java.awt.Dimension(300, 90));
        jList1.setPreferredSize(new java.awt.Dimension(150, 90));
        jScrollPane2.setViewportView(jList1);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.LINE_START);

        jTabbedPane1.addTab("Daily Expenses", jPanel1);

        expensesScroll2.setMaximumSize(new java.awt.Dimension(600, 200));

        dailyExpenses1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clase uno", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        dailyExpenses1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Gasto", "Matriz", "Razón social", "Monto", "Suma de gasto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        dailyExpenses1.setMaximumSize(new java.awt.Dimension(600, 600));
        dailyExpenses1.setMinimumSize(new java.awt.Dimension(600, 60));
        dailyExpenses1.setPreferredSize(new java.awt.Dimension(450, 60));
        expensesScroll2.setViewportView(dailyExpenses1);

        jTabbedPane1.addTab("Monthly Expenses", expensesScroll2);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane14.setMaximumSize(new java.awt.Dimension(100, 100));
        jScrollPane14.setMinimumSize(new java.awt.Dimension(150, 150));
        jScrollPane14.setPreferredSize(new java.awt.Dimension(50, 50));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Title"
            }
        ));
        jTable4.setMinimumSize(new java.awt.Dimension(150, 150));
        jTable4.setPreferredSize(new java.awt.Dimension(50, 50));
        jScrollPane14.setViewportView(jTable4);

        jPanel2.add(jScrollPane14, java.awt.BorderLayout.NORTH);

        jScrollPane15.setPreferredSize(new java.awt.Dimension(50, 50));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jTable5.setMaximumSize(new java.awt.Dimension(150, 150));
        jTable5.setMinimumSize(new java.awt.Dimension(150, 150));
        jTable5.setPreferredSize(new java.awt.Dimension(150, 150));
        jScrollPane15.setViewportView(jTable5);

        jPanel2.add(jScrollPane15, java.awt.BorderLayout.SOUTH);

        jToolBar2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar2.setRollover(true);

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable8.setPreferredSize(new java.awt.Dimension(300, 300));
        jToolBar2.add(jTable8);

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable9.setPreferredSize(new java.awt.Dimension(300, 300));
        jToolBar2.add(jTable9);

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable10.setPreferredSize(new java.awt.Dimension(300, 300));
        jToolBar2.add(jTable10);

        Middle.setViewportView(jToolBar2);

        jPanel2.add(Middle, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Daily Transaccions", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane16.setMaximumSize(new java.awt.Dimension(100, 100));
        jScrollPane16.setMinimumSize(new java.awt.Dimension(150, 150));
        jScrollPane16.setPreferredSize(new java.awt.Dimension(150, 150));

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Title"
            }
        ));
        jTable11.setMinimumSize(new java.awt.Dimension(150, 150));
        jTable11.setPreferredSize(new java.awt.Dimension(150, 150));
        jScrollPane16.setViewportView(jTable11);

        jPanel3.add(jScrollPane16, java.awt.BorderLayout.WEST);

        jScrollPane17.setPreferredSize(new java.awt.Dimension(150, 150));

        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jTable12.setMaximumSize(new java.awt.Dimension(150, 150));
        jTable12.setMinimumSize(new java.awt.Dimension(150, 150));
        jTable12.setPreferredSize(new java.awt.Dimension(150, 150));
        jScrollPane17.setViewportView(jTable12);

        jPanel3.add(jScrollPane17, java.awt.BorderLayout.EAST);

        jToolBar3.setRollover(true);

        jScrollPane19.setPreferredSize(new java.awt.Dimension(300, 300));

        jTable13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable13.setPreferredSize(new java.awt.Dimension(300, 300));
        jScrollPane19.setViewportView(jTable13);

        jToolBar3.add(jScrollPane19);

        jScrollPane20.setPreferredSize(new java.awt.Dimension(300, 300));

        jTable14.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable14.setPreferredSize(new java.awt.Dimension(300, 300));
        jScrollPane20.setViewportView(jTable14);

        jToolBar3.add(jScrollPane20);

        jScrollPane21.setPreferredSize(new java.awt.Dimension(300, 300));

        jTable15.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable15.setPreferredSize(new java.awt.Dimension(300, 300));
        jScrollPane21.setViewportView(jTable15);

        jToolBar3.add(jScrollPane21);

        jScrollPane18.setViewportView(jToolBar3);

        jPanel3.add(jScrollPane18, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("General Matrix", jPanel3);

        add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void monthlyBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyBudgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthlyBudgetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Middle;
    private javax.swing.JCheckBox autoBudgetCheckBox;
    private javax.swing.JLabel autoBudgetLabel;
    private javax.swing.JToolBar autoMonthlyBoudget;
    private javax.swing.JTable dailyExpenses1;
    private javax.swing.JScrollPane expensesScroll2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable13;
    private javax.swing.JTable jTable14;
    private javax.swing.JTable jTable15;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JTable mainTable;
    private javax.swing.JScrollPane mainTableScroll;
    private javax.swing.JTextField monthlyBudget;
    // End of variables declaration//GEN-END:variables
}
